### ISSUE TITLE
Bug: No Validation

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/carserviceapp-core#4]
Scenario: As a User, all the data should be validated
Bug : rating, services, in-charge services, - data not validated.
Without validation all data are entered in DB

![image](https://user-images.githubusercontent.com/22638364/126131301-b33f3d1f-da18-4a03-b77c-f29ee4a1bf4e.png)
![image](https://user-images.githubusercontent.com/22638364/126132596-0c86293c-dc67-4089-a6f1-bbda5ce5318b.png)

**Comment by nandhini2424** [comment]
corrected Validation

**Comment by nandhini2424** [comment]
corrected Validation

**Comment by selvianu** [comment]
Still no validation for customer name(single character), in-charge name(single character), negative values for rating all enters into DB. 

![image](https://user-images.githubusercontent.com/22638364/126298396-c0d44d42-9047-408a-aabe-c808091252f7.png)

![image](https://user-images.githubusercontent.com/22638364/126298480-bf34b483-ad63-49c1-a35a-6eaec48ed1da.png)

**Comment by nandhini2424** [comment]
issue corrected

**Comment by selvianu** [comment]
Working as expected. closed
